### ISSUE TITLE
Poor in app English language support

### ISSUE THREAD

**Issue by Sterh20** [DiskTools/DiskInfo#125]
Great app, but did you test it in non-Chinese languages?
The interface is only partially translated, as seen in the screenshots below, which makes the app unusable.
FYI my OS locale is ru-RU.

![image1](https://github.com/MicaApps/DiskInfo/assets/102921356/f8192f66-5342-48d3-ae88-892f845ab442)
![image](https://github.com/MicaApps/DiskInfo/assets/102921356/cb3724d8-52cd-4cb5-8782-e5757c710eca)
![image](https://github.com/MicaApps/DiskInfo/assets/102921356/fe70e308-9af2-4e0d-a184-9c1b8bd5dbbc)

**Comment by c-michail** [comment]
He has already an issue for help: https://github.com/MicaApps/DiskInfo/issues/84

**Comment by Sterh20** [comment]
@chmichael, thank you for your time. Than I will close this issue as it is kind of duplicate
